version: '3.4'

services:
  geta-tags-sample-web:
    image: ${DOCKER_REGISTRY-}geta-tags-sample-web
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
     - geta-tags-network
    depends_on:
     - geta-tags-sample-db
    volumes: 
      - ../../src/module/:C:/data/
    mac_address: 84-69-95-6C-7F-85
  geta-tags-sample-db:
    image: microsoft/mssql-server-windows-developer:1709
    environment:
     - ACCEPT_EULA=Y
     - sa_password=T@gs19
     - attach_dbs=[{'dbName':'EPiServerDB_dada52e0','dbFiles':['C:\\data\\EPiServerDB_dada52e0.mdf','C:\\data\\EPiServerDB_dada52e0_log.ldf']}]
    volumes: 
      - ../Geta.Tags.Sample/App_Data:C:/data/
    networks:
      - geta-tags-network
networks: 
  geta-tags-network:
    external:
      name: nat
